# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  api:
    taskfile: d1v-api/Taskfile.yaml
    dir: d1v-api

  cli:
    taskfile: d1v-cli/Taskfile.yaml
    dir: d1v-cli

tasks:
  check:
    cmds:
      - cargo check --workspace

  build:
    cmds:
      - cargo build --workspace

  build-release:
    cmds:
      - task: cli:build-release

  run:
    cmds:
      - task: cli:run

  install:
    cmds:
      - task: cli:install

  install-record:
    cmds:
      - task: cli:install-record

  record:
    cmds:
      - task: cli:record

  test:
    cmds:
      - cargo test --workspace
