[package]
name = "d1v-api"
version = "0.1.0"
edition = "2024"

[features]
record = ["dep:ahash"]

[dependencies]
ahash = { version = "0.8", features = ["serde"], optional = true }
parking_lot = "0.12"
reqwest = { version = "0.13", features = ["json", "query"] }
secrecy = { version = "0.10", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tokio = { version = "1.50", features = ["full"] }
url = "2.5"

[dev-dependencies]
httpmock = "0.8"
