# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  check:
    cmds:
      - cargo check

  build:
    cmds:
      - cargo build

  build-release:
    cmds:
      - cargo build --release

  run:
    cmds:
      - cmd: cargo run
        if: "{{ eq (len .CLI_ARGS_LIST) 0 }}"
      - cmd: cargo run -- {{.CLI_ARGS}}
        if: "{{ gt (len .CLI_ARGS_LIST) 0 }}"

  install:
    cmds:
      - cargo install --path .

  test:
    cmds:
      - cargo test
